// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC27aprw-c-c14Q9TvpHCDBUNxcmfw-ELk',
    appId: '1:782393433613:web:63a6053dd4efd97e4bbf44',
    messagingSenderId: '782393433613',
    projectId: 'kitech-solutions-ltd',
    authDomain: 'kitech-solutions-ltd.firebaseapp.com',
    databaseURL: 'https://kitech-solutions-ltd-default-rtdb.firebaseio.com',
    storageBucket: 'kitech-solutions-ltd.firebasestorage.app',
    measurementId: 'G-406ZPZ47QG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATcsfD8kWFyMazhow-u6HonLSYrVXr1zg',
    appId: '1:782393433613:android:31fc0af1b83cc7bd4bbf44',
    messagingSenderId: '782393433613',
    projectId: 'kitech-solutions-ltd',
    databaseURL: 'https://kitech-solutions-ltd-default-rtdb.firebaseio.com',
    storageBucket: 'kitech-solutions-ltd.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWgZ4RhpBELee6mEiE0Idt7wS9AxRgQNQ',
    appId: '1:782393433613:ios:33aed583efe5cc954bbf44',
    messagingSenderId: '782393433613',
    projectId: 'kitech-solutions-ltd',
    databaseURL: 'https://kitech-solutions-ltd-default-rtdb.firebaseio.com',
    storageBucket: 'kitech-solutions-ltd.firebasestorage.app',
    iosClientId: '782393433613-mchlhqvo0imnrmkvv93bful2g56tspcp.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartCropDryer',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWgZ4RhpBELee6mEiE0Idt7wS9AxRgQNQ',
    appId: '1:782393433613:ios:33aed583efe5cc954bbf44',
    messagingSenderId: '782393433613',
    projectId: 'kitech-solutions-ltd',
    databaseURL: 'https://kitech-solutions-ltd-default-rtdb.firebaseio.com',
    storageBucket: 'kitech-solutions-ltd.firebasestorage.app',
    iosClientId: '782393433613-mchlhqvo0imnrmkvv93bful2g56tspcp.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartCropDryer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC27aprw-c-c14Q9TvpHCDBUNxcmfw-ELk',
    appId: '1:782393433613:web:a78d3e04159f5e8d4bbf44',
    messagingSenderId: '782393433613',
    projectId: 'kitech-solutions-ltd',
    authDomain: 'kitech-solutions-ltd.firebaseapp.com',
    databaseURL: 'https://kitech-solutions-ltd-default-rtdb.firebaseio.com',
    storageBucket: 'kitech-solutions-ltd.firebasestorage.app',
    measurementId: 'G-L9J9D6BRNP',
  );
}
